name: storeCi
on:
  pull_request:
    branches:
      - master

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16 ]

    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1 
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test

      - name: Install npm dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint
      
      - name: Run tests
        run: npm run test


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          node-version: ${{ matrix.node-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: lgustavopalmieri/ci-cd-nest:latest
          #lets see that ...